[build]
  command = "echo 'Site is ready'"
  publish = "."

[[notifications]]
  member_emails = ["alimd.pics@gmail.com"]
  
[notifications.outgoing_webhooks]
  [[notifications.outgoing_webhooks.hooks]]
    events = ["form_submission"]
    url = "https://script.google.com/macros/s/AKfycbyXDaMkplH9-ImfYBDlP5Liri3RRCky8wNRn_NAa9yDxA4RcDjmnSWqEWCaIGUwKhkH/exec"
