backend:
  name: github
  repo: amdpics/amdstudio
  branch: main
  auth_endpoint: https://github.com/login/oauth/authorize
  client_id: $OAUTH_CLIENT_ID
  client_secret: $OAUTH_CLIENT_SECRET

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Text", name: "hero", widget: "text"}
          - {label: "About Section", name: "about", widget: "text"}
